name: Build Marp Slides

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Marp CLI via npm (more reliable than action wrapper)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build slides (PDF, HTML, PPTX)
        run: |
          mkdir -p build
          marp slides.md --theme theme/campus-compass.css --allow-local-files --math -o build/slides.pdf
          marp slides.md --theme theme/campus-compass.css --allow-local-files --math -o build/slides.html
          marp slides.md --theme theme/campus-compass.css --allow-local-files --math -o build/slides.pptx

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: marp-slides
          path: build/
